/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccompagnementRouteImport } from './routes/accompagnement'
import { Route as AbonnementRouteImport } from './routes/abonnement'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as CatalogueIdRouteImport } from './routes/catalogue.$id'
import { Route as AppProfilRouteImport } from './routes/app/profil'
import { Route as AppEventsRouteImport } from './routes/app/events'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppClassementRouteImport } from './routes/app/classement'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppRessourcesIndexRouteImport } from './routes/app/ressources/index'
import { Route as AppFormationsIndexRouteImport } from './routes/app/formations/index'
import { Route as AppCommunauteIndexRouteImport } from './routes/app/communaute/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppActualitesIndexRouteImport } from './routes/app/actualites/index'
import { Route as AppRessourcesIdRouteImport } from './routes/app/ressources/$id'
import { Route as AppMembresUserIdRouteImport } from './routes/app/membres/$userId'
import { Route as AppFormationsSlugRouteImport } from './routes/app/formations/$slug'
import { Route as AppCommunautePostIdRouteImport } from './routes/app/communaute/$postId'
import { Route as AppAdminMembersRouteImport } from './routes/app/admin/members'
import { Route as AppAdminInsightsRouteImport } from './routes/app/admin/insights'
import { Route as AppAdminEventsRouteImport } from './routes/app/admin/events'
import { Route as AppAdminClassementRouteImport } from './routes/app/admin/classement'
import { Route as AppAdminAuditLogRouteImport } from './routes/app/admin/audit-log'
import { Route as AppActualitesSlugRouteImport } from './routes/app/actualites/$slug'
import { Route as AppAdminRessourcesIndexRouteImport } from './routes/app/admin/ressources/index'
import { Route as AppAdminFormationsIndexRouteImport } from './routes/app/admin/formations/index'
import { Route as AppAdminCommunityIndexRouteImport } from './routes/app/admin/community/index'
import { Route as AppAdminActualitesIndexRouteImport } from './routes/app/admin/actualites/index'
import { Route as AppAdminRessourcesNewRouteImport } from './routes/app/admin/ressources/new'
import { Route as AppAdminRessourcesIdRouteImport } from './routes/app/admin/ressources/$id'
import { Route as AppAdminFormationsNewRouteImport } from './routes/app/admin/formations/new'
import { Route as AppAdminFormationsIdRouteImport } from './routes/app/admin/formations/$id'
import { Route as AppAdminActualitesNewRouteImport } from './routes/app/admin/actualites/new'
import { Route as AppAdminActualitesIdRouteImport } from './routes/app/admin/actualites/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccompagnementRoute = AccompagnementRouteImport.update({
  id: '/accompagnement',
  path: '/accompagnement',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementRoute = AbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogueRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CatalogueIdRoute = CatalogueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CatalogueRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassementRoute = AppClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppRessourcesIndexRoute = AppRessourcesIndexRouteImport.update({
  id: '/ressources/',
  path: '/ressources/',
  getParentRoute: () => AppRoute,
} as any)
const AppFormationsIndexRoute = AppFormationsIndexRouteImport.update({
  id: '/formations/',
  path: '/formations/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunauteIndexRoute = AppCommunauteIndexRouteImport.update({
  id: '/communaute/',
  path: '/communaute/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppActualitesIndexRoute = AppActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => AppRoute,
} as any)
const AppRessourcesIdRoute = AppRessourcesIdRouteImport.update({
  id: '/ressources/$id',
  path: '/ressources/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMembresUserIdRoute = AppMembresUserIdRouteImport.update({
  id: '/membres/$userId',
  path: '/membres/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppFormationsSlugRoute = AppFormationsSlugRouteImport.update({
  id: '/formations/$slug',
  path: '/formations/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunautePostIdRoute = AppCommunautePostIdRouteImport.update({
  id: '/communaute/$postId',
  path: '/communaute/$postId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMembersRoute = AppAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminInsightsRoute = AppAdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEventsRoute = AppAdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminClassementRoute = AppAdminClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditLogRoute = AppAdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppActualitesSlugRoute = AppActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRessourcesIndexRoute = AppAdminRessourcesIndexRouteImport.update({
  id: '/ressources/',
  path: '/ressources/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFormationsIndexRoute = AppAdminFormationsIndexRouteImport.update({
  id: '/formations/',
  path: '/formations/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCommunityIndexRoute = AppAdminCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminActualitesIndexRoute = AppAdminActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRessourcesNewRoute = AppAdminRessourcesNewRouteImport.update({
  id: '/ressources/new',
  path: '/ressources/new',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRessourcesIdRoute = AppAdminRessourcesIdRouteImport.update({
  id: '/ressources/$id',
  path: '/ressources/$id',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFormationsNewRoute = AppAdminFormationsNewRouteImport.update({
  id: '/formations/new',
  path: '/formations/new',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFormationsIdRoute = AppAdminFormationsIdRouteImport.update({
  id: '/formations/$id',
  path: '/formations/$id',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminActualitesNewRoute = AppAdminActualitesNewRouteImport.update({
  id: '/actualites/new',
  path: '/actualites/new',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminActualitesIdRoute = AppAdminActualitesIdRouteImport.update({
  id: '/actualites/$id',
  path: '/actualites/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/accompagnement': typeof AccompagnementRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/cgu': typeof CguRoute
  '/checkout': typeof CheckoutRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/classement': typeof AppClassementRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/events': typeof AppEventsRoute
  '/app/profil': typeof AppProfilRoute
  '/catalogue/$id': typeof CatalogueIdRoute
  '/app/': typeof AppIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/app/actualites/$slug': typeof AppActualitesSlugRoute
  '/app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/app/admin/classement': typeof AppAdminClassementRoute
  '/app/admin/events': typeof AppAdminEventsRoute
  '/app/admin/insights': typeof AppAdminInsightsRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/communaute/$postId': typeof AppCommunautePostIdRoute
  '/app/formations/$slug': typeof AppFormationsSlugRoute
  '/app/membres/$userId': typeof AppMembresUserIdRoute
  '/app/ressources/$id': typeof AppRessourcesIdRoute
  '/app/actualites/': typeof AppActualitesIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/communaute/': typeof AppCommunauteIndexRoute
  '/app/formations/': typeof AppFormationsIndexRoute
  '/app/ressources/': typeof AppRessourcesIndexRoute
  '/app/admin/actualites/$id': typeof AppAdminActualitesIdRoute
  '/app/admin/actualites/new': typeof AppAdminActualitesNewRoute
  '/app/admin/formations/$id': typeof AppAdminFormationsIdRoute
  '/app/admin/formations/new': typeof AppAdminFormationsNewRoute
  '/app/admin/ressources/$id': typeof AppAdminRessourcesIdRoute
  '/app/admin/ressources/new': typeof AppAdminRessourcesNewRoute
  '/app/admin/actualites/': typeof AppAdminActualitesIndexRoute
  '/app/admin/community/': typeof AppAdminCommunityIndexRoute
  '/app/admin/formations/': typeof AppAdminFormationsIndexRoute
  '/app/admin/ressources/': typeof AppAdminRessourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/accompagnement': typeof AccompagnementRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/checkout': typeof CheckoutRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/classement': typeof AppClassementRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/events': typeof AppEventsRoute
  '/app/profil': typeof AppProfilRoute
  '/catalogue/$id': typeof CatalogueIdRoute
  '/app': typeof AppIndexRoute
  '/catalogue': typeof CatalogueIndexRoute
  '/app/actualites/$slug': typeof AppActualitesSlugRoute
  '/app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/app/admin/classement': typeof AppAdminClassementRoute
  '/app/admin/events': typeof AppAdminEventsRoute
  '/app/admin/insights': typeof AppAdminInsightsRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/communaute/$postId': typeof AppCommunautePostIdRoute
  '/app/formations/$slug': typeof AppFormationsSlugRoute
  '/app/membres/$userId': typeof AppMembresUserIdRoute
  '/app/ressources/$id': typeof AppRessourcesIdRoute
  '/app/actualites': typeof AppActualitesIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/communaute': typeof AppCommunauteIndexRoute
  '/app/formations': typeof AppFormationsIndexRoute
  '/app/ressources': typeof AppRessourcesIndexRoute
  '/app/admin/actualites/$id': typeof AppAdminActualitesIdRoute
  '/app/admin/actualites/new': typeof AppAdminActualitesNewRoute
  '/app/admin/formations/$id': typeof AppAdminFormationsIdRoute
  '/app/admin/formations/new': typeof AppAdminFormationsNewRoute
  '/app/admin/ressources/$id': typeof AppAdminRessourcesIdRoute
  '/app/admin/ressources/new': typeof AppAdminRessourcesNewRoute
  '/app/admin/actualites': typeof AppAdminActualitesIndexRoute
  '/app/admin/community': typeof AppAdminCommunityIndexRoute
  '/app/admin/formations': typeof AppAdminFormationsIndexRoute
  '/app/admin/ressources': typeof AppAdminRessourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/accompagnement': typeof AccompagnementRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/cgu': typeof CguRoute
  '/checkout': typeof CheckoutRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/classement': typeof AppClassementRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/events': typeof AppEventsRoute
  '/app/profil': typeof AppProfilRoute
  '/catalogue/$id': typeof CatalogueIdRoute
  '/app/': typeof AppIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/app/actualites/$slug': typeof AppActualitesSlugRoute
  '/app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/app/admin/classement': typeof AppAdminClassementRoute
  '/app/admin/events': typeof AppAdminEventsRoute
  '/app/admin/insights': typeof AppAdminInsightsRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/communaute/$postId': typeof AppCommunautePostIdRoute
  '/app/formations/$slug': typeof AppFormationsSlugRoute
  '/app/membres/$userId': typeof AppMembresUserIdRoute
  '/app/ressources/$id': typeof AppRessourcesIdRoute
  '/app/actualites/': typeof AppActualitesIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/communaute/': typeof AppCommunauteIndexRoute
  '/app/formations/': typeof AppFormationsIndexRoute
  '/app/ressources/': typeof AppRessourcesIndexRoute
  '/app/admin/actualites/$id': typeof AppAdminActualitesIdRoute
  '/app/admin/actualites/new': typeof AppAdminActualitesNewRoute
  '/app/admin/formations/$id': typeof AppAdminFormationsIdRoute
  '/app/admin/formations/new': typeof AppAdminFormationsNewRoute
  '/app/admin/ressources/$id': typeof AppAdminRessourcesIdRoute
  '/app/admin/ressources/new': typeof AppAdminRessourcesNewRoute
  '/app/admin/actualites/': typeof AppAdminActualitesIndexRoute
  '/app/admin/community/': typeof AppAdminCommunityIndexRoute
  '/app/admin/formations/': typeof AppAdminFormationsIndexRoute
  '/app/admin/ressources/': typeof AppAdminRessourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnement'
    | '/accompagnement'
    | '/app'
    | '/auth'
    | '/catalogue'
    | '/cgu'
    | '/checkout'
    | '/confidentialite'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/admin'
    | '/app/classement'
    | '/app/dashboard'
    | '/app/events'
    | '/app/profil'
    | '/catalogue/$id'
    | '/app/'
    | '/catalogue/'
    | '/app/actualites/$slug'
    | '/app/admin/audit-log'
    | '/app/admin/classement'
    | '/app/admin/events'
    | '/app/admin/insights'
    | '/app/admin/members'
    | '/app/communaute/$postId'
    | '/app/formations/$slug'
    | '/app/membres/$userId'
    | '/app/ressources/$id'
    | '/app/actualites/'
    | '/app/admin/'
    | '/app/communaute/'
    | '/app/formations/'
    | '/app/ressources/'
    | '/app/admin/actualites/$id'
    | '/app/admin/actualites/new'
    | '/app/admin/formations/$id'
    | '/app/admin/formations/new'
    | '/app/admin/ressources/$id'
    | '/app/admin/ressources/new'
    | '/app/admin/actualites/'
    | '/app/admin/community/'
    | '/app/admin/formations/'
    | '/app/admin/ressources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnement'
    | '/accompagnement'
    | '/auth'
    | '/cgu'
    | '/checkout'
    | '/confidentialite'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/classement'
    | '/app/dashboard'
    | '/app/events'
    | '/app/profil'
    | '/catalogue/$id'
    | '/app'
    | '/catalogue'
    | '/app/actualites/$slug'
    | '/app/admin/audit-log'
    | '/app/admin/classement'
    | '/app/admin/events'
    | '/app/admin/insights'
    | '/app/admin/members'
    | '/app/communaute/$postId'
    | '/app/formations/$slug'
    | '/app/membres/$userId'
    | '/app/ressources/$id'
    | '/app/actualites'
    | '/app/admin'
    | '/app/communaute'
    | '/app/formations'
    | '/app/ressources'
    | '/app/admin/actualites/$id'
    | '/app/admin/actualites/new'
    | '/app/admin/formations/$id'
    | '/app/admin/formations/new'
    | '/app/admin/ressources/$id'
    | '/app/admin/ressources/new'
    | '/app/admin/actualites'
    | '/app/admin/community'
    | '/app/admin/formations'
    | '/app/admin/ressources'
  id:
    | '__root__'
    | '/'
    | '/abonnement'
    | '/accompagnement'
    | '/app'
    | '/auth'
    | '/catalogue'
    | '/cgu'
    | '/checkout'
    | '/confidentialite'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/admin'
    | '/app/classement'
    | '/app/dashboard'
    | '/app/events'
    | '/app/profil'
    | '/catalogue/$id'
    | '/app/'
    | '/catalogue/'
    | '/app/actualites/$slug'
    | '/app/admin/audit-log'
    | '/app/admin/classement'
    | '/app/admin/events'
    | '/app/admin/insights'
    | '/app/admin/members'
    | '/app/communaute/$postId'
    | '/app/formations/$slug'
    | '/app/membres/$userId'
    | '/app/ressources/$id'
    | '/app/actualites/'
    | '/app/admin/'
    | '/app/communaute/'
    | '/app/formations/'
    | '/app/ressources/'
    | '/app/admin/actualites/$id'
    | '/app/admin/actualites/new'
    | '/app/admin/formations/$id'
    | '/app/admin/formations/new'
    | '/app/admin/ressources/$id'
    | '/app/admin/ressources/new'
    | '/app/admin/actualites/'
    | '/app/admin/community/'
    | '/app/admin/formations/'
    | '/app/admin/ressources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementRoute: typeof AbonnementRoute
  AccompagnementRoute: typeof AccompagnementRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogueRoute: typeof CatalogueRouteWithChildren
  CguRoute: typeof CguRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accompagnement': {
      id: '/accompagnement'
      path: '/accompagnement'
      fullPath: '/accompagnement'
      preLoaderRoute: typeof AccompagnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement': {
      id: '/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/catalogue/$id': {
      id: '/catalogue/$id'
      path: '/$id'
      fullPath: '/catalogue/$id'
      preLoaderRoute: typeof CatalogueIdRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/app/profil': {
      id: '/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classement': {
      id: '/app/classement'
      path: '/classement'
      fullPath: '/app/classement'
      preLoaderRoute: typeof AppClassementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ressources/': {
      id: '/app/ressources/'
      path: '/ressources'
      fullPath: '/app/ressources/'
      preLoaderRoute: typeof AppRessourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/formations/': {
      id: '/app/formations/'
      path: '/formations'
      fullPath: '/app/formations/'
      preLoaderRoute: typeof AppFormationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/communaute/': {
      id: '/app/communaute/'
      path: '/communaute'
      fullPath: '/app/communaute/'
      preLoaderRoute: typeof AppCommunauteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/actualites/': {
      id: '/app/actualites/'
      path: '/actualites'
      fullPath: '/app/actualites/'
      preLoaderRoute: typeof AppActualitesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ressources/$id': {
      id: '/app/ressources/$id'
      path: '/ressources/$id'
      fullPath: '/app/ressources/$id'
      preLoaderRoute: typeof AppRessourcesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/membres/$userId': {
      id: '/app/membres/$userId'
      path: '/membres/$userId'
      fullPath: '/app/membres/$userId'
      preLoaderRoute: typeof AppMembresUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/formations/$slug': {
      id: '/app/formations/$slug'
      path: '/formations/$slug'
      fullPath: '/app/formations/$slug'
      preLoaderRoute: typeof AppFormationsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/communaute/$postId': {
      id: '/app/communaute/$postId'
      path: '/communaute/$postId'
      fullPath: '/app/communaute/$postId'
      preLoaderRoute: typeof AppCommunautePostIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/members': {
      id: '/app/admin/members'
      path: '/members'
      fullPath: '/app/admin/members'
      preLoaderRoute: typeof AppAdminMembersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/insights': {
      id: '/app/admin/insights'
      path: '/insights'
      fullPath: '/app/admin/insights'
      preLoaderRoute: typeof AppAdminInsightsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/events': {
      id: '/app/admin/events'
      path: '/events'
      fullPath: '/app/admin/events'
      preLoaderRoute: typeof AppAdminEventsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/classement': {
      id: '/app/admin/classement'
      path: '/classement'
      fullPath: '/app/admin/classement'
      preLoaderRoute: typeof AppAdminClassementRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit-log': {
      id: '/app/admin/audit-log'
      path: '/audit-log'
      fullPath: '/app/admin/audit-log'
      preLoaderRoute: typeof AppAdminAuditLogRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/actualites/$slug': {
      id: '/app/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/app/actualites/$slug'
      preLoaderRoute: typeof AppActualitesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/ressources/': {
      id: '/app/admin/ressources/'
      path: '/ressources'
      fullPath: '/app/admin/ressources/'
      preLoaderRoute: typeof AppAdminRessourcesIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/formations/': {
      id: '/app/admin/formations/'
      path: '/formations'
      fullPath: '/app/admin/formations/'
      preLoaderRoute: typeof AppAdminFormationsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/community/': {
      id: '/app/admin/community/'
      path: '/community'
      fullPath: '/app/admin/community/'
      preLoaderRoute: typeof AppAdminCommunityIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/actualites/': {
      id: '/app/admin/actualites/'
      path: '/actualites'
      fullPath: '/app/admin/actualites/'
      preLoaderRoute: typeof AppAdminActualitesIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/ressources/new': {
      id: '/app/admin/ressources/new'
      path: '/ressources/new'
      fullPath: '/app/admin/ressources/new'
      preLoaderRoute: typeof AppAdminRessourcesNewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/ressources/$id': {
      id: '/app/admin/ressources/$id'
      path: '/ressources/$id'
      fullPath: '/app/admin/ressources/$id'
      preLoaderRoute: typeof AppAdminRessourcesIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/formations/new': {
      id: '/app/admin/formations/new'
      path: '/formations/new'
      fullPath: '/app/admin/formations/new'
      preLoaderRoute: typeof AppAdminFormationsNewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/formations/$id': {
      id: '/app/admin/formations/$id'
      path: '/formations/$id'
      fullPath: '/app/admin/formations/$id'
      preLoaderRoute: typeof AppAdminFormationsIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/actualites/new': {
      id: '/app/admin/actualites/new'
      path: '/actualites/new'
      fullPath: '/app/admin/actualites/new'
      preLoaderRoute: typeof AppAdminActualitesNewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/actualites/$id': {
      id: '/app/admin/actualites/$id'
      path: '/actualites/$id'
      fullPath: '/app/admin/actualites/$id'
      preLoaderRoute: typeof AppAdminActualitesIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditLogRoute: typeof AppAdminAuditLogRoute
  AppAdminClassementRoute: typeof AppAdminClassementRoute
  AppAdminEventsRoute: typeof AppAdminEventsRoute
  AppAdminInsightsRoute: typeof AppAdminInsightsRoute
  AppAdminMembersRoute: typeof AppAdminMembersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminActualitesIdRoute: typeof AppAdminActualitesIdRoute
  AppAdminActualitesNewRoute: typeof AppAdminActualitesNewRoute
  AppAdminFormationsIdRoute: typeof AppAdminFormationsIdRoute
  AppAdminFormationsNewRoute: typeof AppAdminFormationsNewRoute
  AppAdminRessourcesIdRoute: typeof AppAdminRessourcesIdRoute
  AppAdminRessourcesNewRoute: typeof AppAdminRessourcesNewRoute
  AppAdminActualitesIndexRoute: typeof AppAdminActualitesIndexRoute
  AppAdminCommunityIndexRoute: typeof AppAdminCommunityIndexRoute
  AppAdminFormationsIndexRoute: typeof AppAdminFormationsIndexRoute
  AppAdminRessourcesIndexRoute: typeof AppAdminRessourcesIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditLogRoute: AppAdminAuditLogRoute,
  AppAdminClassementRoute: AppAdminClassementRoute,
  AppAdminEventsRoute: AppAdminEventsRoute,
  AppAdminInsightsRoute: AppAdminInsightsRoute,
  AppAdminMembersRoute: AppAdminMembersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminActualitesIdRoute: AppAdminActualitesIdRoute,
  AppAdminActualitesNewRoute: AppAdminActualitesNewRoute,
  AppAdminFormationsIdRoute: AppAdminFormationsIdRoute,
  AppAdminFormationsNewRoute: AppAdminFormationsNewRoute,
  AppAdminRessourcesIdRoute: AppAdminRessourcesIdRoute,
  AppAdminRessourcesNewRoute: AppAdminRessourcesNewRoute,
  AppAdminActualitesIndexRoute: AppAdminActualitesIndexRoute,
  AppAdminCommunityIndexRoute: AppAdminCommunityIndexRoute,
  AppAdminFormationsIndexRoute: AppAdminFormationsIndexRoute,
  AppAdminRessourcesIndexRoute: AppAdminRessourcesIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppClassementRoute: typeof AppClassementRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventsRoute: typeof AppEventsRoute
  AppProfilRoute: typeof AppProfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppActualitesSlugRoute: typeof AppActualitesSlugRoute
  AppCommunautePostIdRoute: typeof AppCommunautePostIdRoute
  AppFormationsSlugRoute: typeof AppFormationsSlugRoute
  AppMembresUserIdRoute: typeof AppMembresUserIdRoute
  AppRessourcesIdRoute: typeof AppRessourcesIdRoute
  AppActualitesIndexRoute: typeof AppActualitesIndexRoute
  AppCommunauteIndexRoute: typeof AppCommunauteIndexRoute
  AppFormationsIndexRoute: typeof AppFormationsIndexRoute
  AppRessourcesIndexRoute: typeof AppRessourcesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppClassementRoute: AppClassementRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventsRoute: AppEventsRoute,
  AppProfilRoute: AppProfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppActualitesSlugRoute: AppActualitesSlugRoute,
  AppCommunautePostIdRoute: AppCommunautePostIdRoute,
  AppFormationsSlugRoute: AppFormationsSlugRoute,
  AppMembresUserIdRoute: AppMembresUserIdRoute,
  AppRessourcesIdRoute: AppRessourcesIdRoute,
  AppActualitesIndexRoute: AppActualitesIndexRoute,
  AppCommunauteIndexRoute: AppCommunauteIndexRoute,
  AppFormationsIndexRoute: AppFormationsIndexRoute,
  AppRessourcesIndexRoute: AppRessourcesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CatalogueRouteChildren {
  CatalogueIdRoute: typeof CatalogueIdRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
}

const CatalogueRouteChildren: CatalogueRouteChildren = {
  CatalogueIdRoute: CatalogueIdRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
}

const CatalogueRouteWithChildren = CatalogueRoute._addFileChildren(
  CatalogueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementRoute: AbonnementRoute,
  AccompagnementRoute: AccompagnementRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogueRoute: CatalogueRouteWithChildren,
  CguRoute: CguRoute,
  CheckoutRoute: CheckoutRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
